export const environment = {
  API_URL: 'http://localhost:5000',
  PUBLIC_KEY: '-----BEGIN PUBLIC KEY-----MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgFDpsC5yqsZ5xm5rhvPIzJawklx39iZt3L4bnXJeTWDE5UIdDqYvmq5BhGJXgA9QmLe4Fk6LEU0fJKkrZ6YRMfPD1rUxQcNyYRspjzwuvIjWlFKvu/mMR+9bXB5J3K9ALx1EKz2r2VEhIu6J2zE+BT/d2fRzm2bKZLJMMrYs1U/pAgMBAAE=-----END PUBLIC KEY-----'
}
